config/routes.rb
Rails.application.routes.draw do
  get 'parsing_jobs/new'
  post 'parsing_jobs', to: 'parsing_jobs#create'
  get 'parsing_jobs', to: 'parsing_jobs#index'
  resources :characteristics_products
  resources :products
  resources :characteristics
  resources :measure_units
  resources :subcategories
  resources :categories
end

app/models/characteristic.rb
class Characteristic < ApplicationRecord
  belongs_to :measure_unit, optional: true
  belongs_to :subcategory, optional: true
  has_many :product, through: :characteristics_products
  has_many :characteristics_products
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: %i[ show edit update destroy ]

  # GET /characteristics or /characteristics.json
  def index
    @characteristics = Characteristic.all
  end

  # GET /characteristics/1 or /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics or /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to @characteristic, notice: "Characteristic was successfully created." }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1 or /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to @characteristic, notice: "Characteristic was successfully updated." }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1 or /characteristics/1.json
  def destroy
    @characteristic.destroy
    respond_to do |format|
      format.html { redirect_to characteristics_url, notice: "Characteristic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def characteristic_params
      params.require(:characteristic).permit(:name, :measure_unit_id, :subcategory_id)
    end
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/views/characteristics/_form.html.erb
<%= form_with(model: characteristic) do |form| %>
  <% if characteristic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(characteristic.errors.count, "error") %> prohibited this characteristic from being saved:</h2>

      <ul>
        <% characteristic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :measure_unit_id %>
    <%= form.text_field :measure_unit_id %>
  </div>

  <div class="field">
    <%= form.label :subcategory_id %>
    <%= form.text_field :subcategory_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<h1>Editing Characteristic</h1>

<%= render 'form', characteristic: @characteristic %>

<%= link_to 'Show', @characteristic %> |
<%= link_to 'Back', characteristics_path %>

app/views/characteristics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characteristics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Measure unit</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characteristics.each do |characteristic| %>
      <tr>
        <td><%= characteristic.name %></td>
        <td><%= characteristic.measure_unit.name %></td>
        <td><%= characteristic.subcategory.name %></td>
        <td><%= link_to 'Show', characteristic %></td>
        <td><%= link_to 'Edit', edit_characteristic_path(characteristic) %></td>
        <td><%= link_to 'Destroy', characteristic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Characteristic', new_characteristic_path %>

app/views/characteristics/new.html.erb
<h1>New Characteristic</h1>

<%= render 'form', characteristic: @characteristic %>

<%= link_to 'Back', characteristics_path %>

app/views/characteristics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @characteristic.name %>
</p>

<p>
  <strong>Measure unit:</strong>
  <%= @characteristic.measure_unit.name %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @characteristic.subcategory.name %>
</p>

<%= link_to 'Edit', edit_characteristic_path(@characteristic) %> |
<%= link_to 'Back', characteristics_path %>