config/routes.rb
Rails.application.routes.draw do
  get 'parsing_jobs/new'
  post 'parsing_jobs', to: 'parsing_jobs#create'
  get 'parsing_jobs', to: 'parsing_jobs#index'
  resources :characteristics_products
  resources :products
  resources :characteristics
  resources :measure_units
  resources :subcategories
  resources :categories
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[ show edit update destroy ]

  # GET /subcategories or /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1 or /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories or /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: "Subcategory was successfully created." }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1 or /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: "Subcategory was successfully updated." }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1 or /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: "Subcategory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_with(model: subcategory) do |form| %>
  <% if subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
        <% subcategory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subcategories/_subcategory.html.erb
<div class="col-4">
  <div class="card">
    <a href= <%= subcategory_path(subcategory) %> >
    <img class="card-img-top" src=<%= asset_path("subcategory_cards/#{subcategory.id}.png") %> >
    <div class="card-body">
      <h5 class="card-title"><%= subcategory.name %></h5>
    </div>
  </a>
  </div>
</div>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.category.name %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<ol class="breadcrumb shadow-sm">
    <li class="breadcrumb-item"><a href=<%= products_path %>>Домой</a></li>
    <li class="breadcrumb-item"><a href=<%= category_path(@subcategory.category) %>><%= @subcategory.category.name %></a></li>
    <li class="breadcrumb-item active"><%= @subcategory.name %></li>
</ol>
<p id="notice"><%= notice %></p>

<div class="row">
  <%= render partial: 'products/product', collection: @subcategory.products %>
</div>