config/routes.rb
Rails.application.routes.draw do
  get 'parsing_jobs/new'
  post 'parsing_jobs', to: 'parsing_jobs#create'
  get 'parsing_jobs', to: 'parsing_jobs#index'
  resources :characteristics_products
  resources :products
  resources :characteristics
  resources :measure_units
  resources :subcategories
  resources :categories
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory
  has_many :products, through: :characteristics_products
  has_many :characteristics_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :subcategory_id, :picture_url)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :subcategory_id %>
    <%= form.text_field :subcategory_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-4">
  <div class="card">
    <a href= <%= product_path(product) %> >
    <img class="card-img-top" src=<%= product.picture_url || asset_path("product_cards/#{product.id}.jpg")   %> >
    <div class="card-body">
      <h5 class="card-title"><%= product.name %></h5>
      <h6 class="card-subtitle mb-2 "><%= product.price %> руб.</h6>
    </div>
  </a>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.subcategory.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<ol class="breadcrumb shadow-sm">
    <li class="breadcrumb-item"><a href=<%= @products_path %>>Домой</a></li>
    <li class="breadcrumb-item"><a href=<%= category_path(@product.subcategory.category) %>><%= @product.subcategory.category.name %></a></li>
    <li class="breadcrumb-item"><a href=<%= subcategory_path(@product.subcategory) %>><%= @product.subcategory.name %></a></li>
    <li class="breadcrumb-item active"><%= @product.name %></li>
</ol>
<p id="notice"><%= notice %></p>

<h3>
  <%= @product.name %>
</h3>

<img class="" src=<%= @product.picture_url || asset_path("product_cards/#{@product.id}.jpg")   %> >
<p>
  <strong>Цена:</strong>
  <%= @product.price %>
</p>
<button type="button" class="btn btn-success">Добавить в корзину</button>
<button type="button" class="btn btn-outline-success">Купить в 1 клик</button>


<div class="specs">
  <h2>Характеристики:</h2>
    <% @product.characteristics_products.each do |spec| %>
      <%= spec.characteristic.name %>: 
      <%= spec.value %> 
      <%= spec.characteristic.measure_unit.name %>
      <br />
    <% end %>
</div>